version: "3.9"
services:
  backend:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/cloud_security?retryWrites=true&w=majority
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: streamlit run frontend/app.py --server.port 8501
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"