version: "3.9"

services:
  backend:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-service-account.json
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
    volumes:
      - ./backend:/app
      - ./gcp_access_token.json:/app/gcp-service-account.json  # Map GCP service account JSON file
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: streamlit run frontend/app.py --server.port 8501
    environment:
      STREAMLIT_SERVER_PORT: 8501
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"