services:
  - name: cloud-data-backend
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - fromGroup: env  # References the `env` group you've created
    healthCheckPath: "/docs"

